# sqlite datasource
#spring.datasource.url=jdbc:sqlite:./data/todo.db
#spring.datasource.driver-class-name=org.sqlite.JDBC

# postgresql
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/tododb}
spring.datasource.username=${SPRING_DATASOURCE_URL_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_URL_PASSWORD:password}


# jpa
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false