spring.application.name=todo

# port
server.port=8080

# Sping Batch meta table auto-creation
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Default Profile(아무설정 없을 때 local을 바라보게 함)
#spring.profiles.active=local